[package]
name = "literate-potato"
version = "0.1.0"
edition = "2024"

[dependencies]
poise = "0.6.1"
serenity = "0.12"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
reqwest = "0.11"
scraper = "0.17"